### ISSUE TITLE
Switch from circle to Github actions

### ISSUE THREAD

**Issue by marbar3778** [CosmWasm/cosmwasm-template#27]
Github Actions has nice support for rust: https://github.com/actions-rs

Currently, in the circle ci config, a rust version is being set, this may be on purpose but if not then switching to GitHub actions would make sense. Also easier for people who use this repo to get started with ci when its Github actions (they just have to push to a repo and the rest is handled by Github)

If people are up for this change I can knock this out quickly

**Comment by webmaster128** [comment]
Hi @marbar3778! This repo itself is tested by AppVeyor (because it allows us to move the config file into an [ignored](https://github.com/confio/cosmwasm-template/blob/master/.genignore) `meta` folder). The circleci config is an offer for users who want to test their project using circleci. It would be simple to add a GitHub Actions configuration as well. Then the user can choose which one to use and which one to delete.

Both Ethan and me don't have experience with GitHub Actions but this is definitely a good chance to give it a try. Would you like to propose a config that does more or less the same that the currect circleci config does?

**Comment by marbar3778** [comment]
yes i can do this
